### ISSUE TITLE
Pull Requests with different branches 

### ISSUE THREAD

**Issue by pamaph20** [kevinaangstadt/CS340-S23-Notes#63] opened 2023-03-06 01:25 UTC
As seen from looking through the pull requests menu, there has been disparity on which branches pull requests should be made from. As outlined in the project outline, "Create your pull requests from non-main branches.". Lets make sure we are all submitting pull requests from a separate branch other than our main to keep everything consistent.

For example--

Add more commits by pushing to the [main](https://github.com/pamaph20/CS340-S23-Notes) branch on [pamaph20/CS340-S23-Notes](https://github.com/pamaph20/CS340-S23-Notes).

**Comment by kevinaangstadt** [comment] 2023-03-26 18:52
Good observation and duplicate of #58

**Closed by kevinaangstadt** 2023-03-26 18:52 UTC
